// Table and API fetch pagination presets

export const PAGINATION = {
  TABLE_PAGE_SIZE_OPTIONS: [10, 25, 50, 100] as const,
  DEFAULT_TABLE_PAGE_SIZE: 25,
  AUDIT_PAGE_SIZE_OPTIONS: [25, 50, 100, 200] as const,
  DEFAULT_AUDIT_PAGE_SIZE: 25,
  REGISTRY_FETCH_PAGE_SIZE: 100,
  MAX_REGISTRY_FETCH_PAGES: 500,
  USER_LIST_PAGE_SIZE: 100,
} as const;

export const DEFAULT_PAGE_SIZE_OPTIONS = PAGINATION.TABLE_PAGE_SIZE_OPTIONS;
