// Inference permission ID labels

/** Inference permission IDs → display names when GET /permissions is unavailable. */
export const INFERENCE_PERMISSION_LABEL_BY_ID: Record<number, string> = {
  60: "NMT.INFERENCE",
  61: "ASR.INFERENCE",
  62: "TTS.INFERENCE",
  63: "LLM.INFERENCE",
  64: "NER.INFERENCE",
  65: "OCR.INFERENCE",
  66: "TRANSLITERATION.INFERENCE",
  67: "LANGUAGE-DETECTION.INFERENCE",
  68: "LANGUAGE-DIARIZATION.INFERENCE",
  69: "SPEAKER-DIARIZATION.INFERENCE",
  70: "AUDIO-LANG-DETECTION.INFERENCE",
  71: "PIPELINE.INFERENCE",
};
